### ISSUE TITLE
transport -08 using values 1F, 1E and 1D for types

### ISSUE THREAD

**Issue by ronieven** [britram/draft-trammell-quic-spin#11]
These values are a problem for spin bit support

**Comment by britram** [comment]
Yep, but we can push this down to 0xF, 0xE, and 0xD (see https://britram.github.io/draft-trammell-quic-spin/draft-trammell-quic-spin.html#proposed-short-header-format-including-spin-bit), and I'm not sure that whatever transport version we end up with will have types as we know them, anyway (see https://github.com/quicwg/base-drafts/issues/989).

In any case, adding a spin bit to the short header will require modifications to the short header, and which bit spins is then basically an engineering problem. So I'm not worried here....
