### ISSUE TITLE
Third-party oversight as a use case?

### ISSUE THREAD

**Issue by britram** [britram/draft-trammell-quic-spin#6]
We briefly discussed whether or not measurements for oversight of regulatory requirements, e.g. network neutrality, were a use case for passive RTT. Is this something we want to add to the document?

**Comment by ronieven** [comment]
I think that we should try to have any use case that we know of. So far on the main mailing list I see people arguing about any use case we make arguing its validity. We need to reflect what service provider encounter when doing their business

**Comment by thomas-fossati** [comment]
I'm talking to Klaus Nieminen of the Finnish communications regulatory authority about this at the minute.

I'll touch base as soon as our discussion comes to a conclusion.

**Comment by thomas-fossati** [comment]
Extract from Klaus' email: "[...] we are mainly targeting client based measurements so it seems that the spin-bit technique won't help us as we are not targeting for passive probes in the network."

So, apparently NN - at least in the EU - is not a thing.
